services:
  nextjs:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/inventory-system?schema=public
    networks:
      - backend

  postgres:
    build: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory-system
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

networks:
  backend:

volumes:
  postgresql-data:



