import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import ReduxProvider from "@/components/redux-provider";
import Notification from "@/components/notification";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center box-border`}
        >
          <Header />
          <Notification />
          <div className="w-full max-w-[1000px] flex flex-col flex-1 items-center box-border pt-4">
            {children}
          </div>
          <Footer />
        </body>
      </ReduxProvider>
    </html>
  );
}
